# -*- coding: utf-8 -*-
"""Desafio: Criando um sistema bancario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxuadM39e9RvM_SogXmDTO48GiTDc3Du
"""

op = 0
saldo = 0
historico_extrato = []
qt_saque = 3


print("Operações:")
print("1 - Depósito")
print("2 - Saque")
print("3 - Extrato")
print("4 - Cancelar")

def deposito(valor_deposito):
  global saldo
  saldo += valor_deposito
  historico_extrato.append(("Depósito de R$ = {:.2f}".format(valor_deposito)))
  print("Depósito concluido!")

def saque(valor_saque):
  global qt_saque, saldo
  if(qt_saque == 0):
      print("Você atingiu seu limite de saque diário! Tente novamente mais tarde!")
  else:
    if (saldo < valor_saque):
      print("Não é possível sacar o dinheiro! Saldo Insuficiente")
    elif(valor_saque <= 500 and valor_saque > 0):
        saldo = saldo - valor_saque
        historico_extrato.append(("Saque de R$ = {:.2f}".format(valor_saque)))
        qt_saque -= 1
        print("Saque concluido!")

    elif(valor_saque > 500):
      print("Valor de saque acima de R$ 500, cancelando a operação!")

def extrato():
  if not historico_extrato:
    print("Não foram realizadas movimentações!")
  else:
    for i in range(len(historico_extrato)):
      print(historico_extrato[i])






while True:
  print("Saldo total: R$ {:.2f}".format(saldo))
  op = int(input("Qual operação deseja realizar?  "))

  if(op == 1):
    print("Operação de Depósito")
    deposito(float(input("Digite o valor a ser depositado: ")))

  elif(op == 2):
    print("Operação de Saque")
    saque(float(input("Digite um valor de saque até R$ 500.00  ")))

  elif(op == 3):
    print("Extrato")
    extrato()

  elif(op == 4):
    print("Saindo da aplicação, muito obrigado por utilizar nossos serviços!")
    break


  else:
    print("Você não escolheu uma opção válida, tente de novo")





